routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false, 'reset' => false, 'verify' => false]);

Route::group(['middleware' => ['auth', 'verified']], function () {
    Route::get('/', function () {
        return redirect(route('home'));
    });

    Route::get('/home', 'ApplicationController@index')->name('home');

    Route::resource('/prestadores_servicos', '\App\Http\Controllers\PrestadorServicoController');
    Route::get('/prestadores_servicos/buscar', '\App\Http\Controllers\PrestadorServicoController@search')->name('prestadores_servicos.search');

    Route::get('/contratos', '\App\Http\Controllers\App\ContratoController@index');
    Route::get('/contratos/create', '\App\Http\Controllers\App\ContratoController@create')->name('contratos.create');

    Route::group([], function () {
        Route::get('/admin', 'AdminController@index')->name('admin');

        Route::group(['prefix' => 'admin'], function () {
            Route::resource('/empresas', '\App\Http\Controllers\Admin\EmpresaController')->except(['show']);
            Route::get('/empresas/buscar', '\App\Http\Controllers\Admin\EmpresaController@search')->name('empresas.search');

            Route::resource('/usuarios', '\App\Http\Controllers\Admin\UsuarioController')->except(['show']);
            Route::get('/usuarios/buscar', '\App\Http\Controllers\Admin\UsuarioController@search')->name('usuarios.search');

            Route::resource('/aliquota_imposto_renda', '\App\Http\Controllers\Admin\AliquotaImpostoRendaController')->except(['show']);
        });
    });
});

app/Http/Controllers/Admin/EmpresaController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Model\Empresa;
use App\Model\Usuario;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class EmpresaController extends Controller
{
    protected $perPage = 20;

    /**
     * Display a paginated listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $perPage = $this->perPage;
        $page = $request->page ? $request->page : 1;
        $empresas = Empresa::paginate($this->perPage);

        return view('admin.empresas.index', compact('empresas', 'page', 'perPage'))->with('query', $request->q);
    }

    /**
     * Display a filtered paginated listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function search(Request $request)
    {
        $perPage = $this->perPage;
        $page = $request->page ? $request->page : 1;
        $query = '%' . $request->q . '%';

        $empresas = Empresa::where('cnpj', 'LIKE', $query)
            ->orWhere('nome', 'LIKE', $query)
            ->paginate($this->perPage);

        return view('admin.empresas.index', compact('empresas', 'page', 'perPage'))->with('query', $request->q);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $cidades = \App\Model\Cidade::where('estado_id', 22)->get();

        return view('admin.empresas.create', compact('cidades'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'cnpj' => 'required|string|unique:empresas|size:14',
            'nome' => 'required|string|max:255',
            'cep' => 'required|string|size:8',
            'endereco' => 'required|string|max:255',
            'numero' => 'required|string|max:6',
            'bairro' => 'required|string|max:255',
            'cidade_id' => 'required|integer',
            'responsavel' => 'required|string|max:255',
            'telefone' => 'required|string|between:10,11',
            'email' => 'required|string',
            'senha' => 'required|string|min:6'

        ]);

        $usuarioData = [
            'nome' => $data['responsavel'],
            'email' => $data['email'],
            'telefone' => $data['telefone'],
            'password' => Hash::make($data['senha'])
        ];

        $usuario = Usuario::create($usuarioData);

        $data['responsavel_id'] = $usuario->id;

        $empresa = Empresa::create($data);

        $status = 'A empresa ' . $empresa->nome . ' foi cadastrada com sucesso.';

        return redirect(route('empresas.index'))->with('status', $status);
    }

    public function edit($id)
    {
        $empresa = Empresa::findOrfail($id);
        $cidades = \App\Model\Cidade::where('estado_id', 22)->get();
        $usuarios = \App\Model\Usuario::all();

        return view('admin.empresas.edit', compact('empresa', 'cidades', 'usuarios'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $data = $request->validate([
            'cnpj' => 'required|string|size:14',
            'nome' => 'required|string|max:255',
            'cep' => 'required|string|size:8',
            'endereco' => 'required|string|max:255',
            'numero' => 'required|string|max:6',
            'bairro' => 'required|string|max:255',
            'cidade_id' => 'required|integer',
            'responsavel_id' => 'required|integer'
        ]);

        $empresa = Empresa::findOrfail($request->empresa)->update($data);

        $status = 'A empresa ' . $empresa['nome'] . ' foi atualizada com sucesso.';

        return redirect(route('empresas.index'))->with('status', $status);
    }

    public function destroy($id)
    {
        $empresa = Empresa::findOrfail($id);

        $empresa->delete();

        return redirect(route('empresas.index'));
    }
}

resources/views/admin/empresas/create.blade.php
@extends('layouts.admin')
@section('main')
<section class="content">
	<div class="box box-primary">
		<div class="box-header">
			<h3>Cadastrar Empresa</h3>
		</div>
		<div class="box-body">
			<form action="{{ route('empresas.store') }}" method="post">
				@csrf
				<input type="hidden" name="empresa_id">

				<div class="row">
					<div class="form-group col-sm-4">
						<label for="">CNPJ</label>
						<input type="cnpj" name="cnpj" id="cnpj" class="form-control" placeholder="00.000.000/0000-00">
						@error('cnpj')
						<div class="text-danger">{{ $message }}</div>
						@enderror
					</div>

					<div class="form-group col-sm-8">
						<label for="">Nome</label>
						<input type="text" name="nome" class="form-control" placeholder="Razão social">
						@error('nome')
						<div class="text-danger">{{ $message }}</div>
						@enderror
					</div>
				</div>

				<div class="row">
					<div class="form-group col-sm-3">
						<label for="cep">CEP</label>
						<input type="text" class="form-control" name="cep" id="cep" placeholder="00000-000">
						@error('cep')
						<div class="text-danger">{{ $message }}</div>
						@enderror
					</div>
					<div class="form-group col-sm-7">
						<label for="endereco">Endereço</label>
						<input type="text" class="form-control" name="endereco" id="endereco" placeholder="Ex.: Av. Brasil T2.">
						@error('endereco')
						<div class="text-danger">{{ $message }}</div>
						@enderror
					</div>
					<div class="form-group col-sm-2">
						<label for="numero">Numero</label>
						<input type="text" class="form-control" name="numero" id="numero">
						@error('numero')
						<div class="text-danger">{{ $message }}</div>
						@enderror
					</div>
				</div>

				<div class="row">
					<div class="form-group col-sm-6">
						<label for="bairro">Bairro</label>
						<input type="text" class="form-control" name="bairro" id="bairro">
						@error('bairro')
						<div class="text-danger">{{ $message }}</div>
						@enderror
					</div>
					<div class="form-group col-sm-6">
						<label for="cidade">Cidade</label>
						<select name="cidade" id="" class="form-control">
							<option value="null">...</option>
							@foreach ($cidades as $cidade)
							<option value="{{$cidade->id}}">{{$cidade->nome}}</option>
							@endforeach
						</select>
						@error('cidade')
						<div class="text-danger">{{ $message }}</div>
						@enderror
					</div>
				</div>

				<div class="row">
					<div class="form-group col-sm-8">
						<label for="responsavel">Responsável</label>
						<input type="text" class="form-control" name="responsavel" id="responsavel" placeholder="Insira o nome do responsável pela empresa">
						@error('responsavel')
						<div class="text-danger">{{ $message }}</div>
						@enderror
					</div>
					<div class="form-group col-sm-4">
						<label for="telefone">Telefone</label>
						<input type="text" class="form-control" name="telefone" id="telefone" placeholder="(00) 0000-0000">
						@error('telefone')
						<div class="text-danger">{{ $message }}</div>
						@enderror
					</div>
				</div>

				<div class="row">
					<div class="form-group col-sm-8">
						<label for="email">Email</label>
						<input type="email" class="form-control" name="email" id="email">
						@error('email')
						<div class="text-danger">{{ $message }}</div>
						@enderror
					</div>
					<div class="form-group col-sm-4">
						<label for="">Senha</label>
						<input type="password" name="senha" class="form-control" placeholder="Senha">
						@error('senha')
						<div class="text-danger">{{ $message }}</div>
						@enderror
					</div>
				</div>

				<div class="form-group">
					<button class="btn btn-primary" type="submit">Salvar</button>

					<a href="{{url('/admin/empresas')}}">
						<button class="btn btn-default" type="button">Cancelar</button>
					</a>
				</div>
			</form>
		</div>
	</div>

	<script src="{{ URL::asset('js/InputMasks.js') }}"></script>
</section>
@endsection

resources/views/admin/empresas/edit.blade.php
@extends('layouts.admin')
@section('main')
<section class="content">
	<div class="box box-primary">
		<div class="box-header">
			<h3>Editar Empresa ({{ $empresa->nome }})</h3>
		</div>
		<div class="box-body">
			<form action="{{route('empresas.update', [$empresa->id])}}" method="post">
				@method('PUT')
				@csrf
				<input type="hidden" name="empresa_id" value="{{$empresa->id}}">

				<div class="row">
					<div class="form-group col-sm-4">
						<label for="">CNPJ</label>
						<input readonly type="cnpj" name="cnpj" id="cnpj" value="{{$empresa->cnpj}}" class="form-control" placeholder="Ex.: 00.000.00/0000-00">
						@error('cnpj')
						<div class="text-danger">{{ $message }}</div>
						@enderror
					</div>

					<div class="form-group col-sm-8">
						<label for="">Nome</label>
						<input type="text" name="nome" value="{{$empresa->nome}}" class="form-control" placeholder="Razão social">
						@error('nome')
						<div class="text-danger">{{ $message }}</div>
						@enderror
					</div>
				</div>

				<div class="row">
					<div class="form-group col-sm-3">
						<label for="cep">CEP</label>
						<input type="text" class="form-control" name="cep" value="{{$empresa->cep}}" id="cep" placeholder="Ex.: 00000-000">
						@error('cep')
						<div class="text-danger">{{ $message }}</div>
						@enderror
					</div>
					<div class="form-group col-sm-7">
						<label for="endereco">Endereço</label>
						<input type="text" class="form-control" name="endereco" value="{{$empresa->endereco}}" id="endereco" placeholder="Ex.: Av. Brasil T2.">
						@error('endereco')
						<div class="text-danger">{{ $message }}</div>
						@enderror
					</div>
					<div class="form-group col-sm-2">
						<label for="numero">Numero</label>
						<input type="text" class="form-control" name="numero" value="{{$empresa->numero}}" id="numero">
						@error('numero')
						<div class="text-danger">{{ $message }}</div>
						@enderror
					</div>
				</div>

				<div class="row">
					<div class="form-group col-sm-6">
						<label for="bairro">Bairro</label>
						<input type="text" class="form-control" name="bairro" value="{{$empresa->bairro}}" id="bairro">
						@error('bairro')
						<div class="text-danger">{{ $message }}</div>
						@enderror
					</div>
					<div class="form-group col-sm-6">
						<label for="cidade">Cidade</label>
						<select name="cidade" id="" class="form-control">
							<option value="null">...</option>
							@foreach ($cidades as $cidade)
							@if($cidade->id == $empresa->cidade_id)
							<option value="{{$cidade->id}}" selected>{{$cidade->nome}}</option>
							@else
							<option value="{{$cidade->id}}">{{$cidade->nome}}</option>
							@endif
							@endforeach
						</select>
						@error('cidade')
						<div class="text-danger">{{ $message }}</div>
						@enderror
					</div>
				</div>

				<div class="row">
					<div class="form-group col-sm-6">
						<label for="responsavel">
							Responsável
							(<a href="{{ route('usuarios.edit', $empresa->responsavel_id) }}">Editar usuário</a>)
						</label>
						<select name="responsavel_id" id="" class="form-control">
							<option value="null">...</option>
							@foreach ($usuarios as $usuario)
							@if($usuario->id == $empresa->responsavel_id)
							<option value="{{$usuario->id}}" selected>{{ $usuario->nome }}</option>
							@else
							<option value="{{$usuario->id}}">{{ $usuario->nome }}</option>
							@endif
							@endforeach
						</select>
						@error('responsavel_id')
						<div class="text-danger">{{ $message }}</div>
						@enderror
					</div>
				</div>

				<div class="form-group">
					<button class="btn btn-primary" type="submit">Salvar</button>

					<a href="{{url('/admin/empresas')}}">
						<button class="btn btn-default" type="button">Cancelar</button>
					</a>
				</div>
			</form>
		</div>
	</div>

	<script src="{{ URL::asset('js/InputMasks.js') }}"></script>
</section>
@endsection

resources/views/admin/empresas/index.blade.php
@extends('layouts.admin')
@section('main')
<section class="content">
	<div class="box box-primary">
		<div class="box-header">
			<h3>Empresas</h3>
			@if (session('status'))
				<div class="alert alert-success">
					{{ session('status') }}
				</div>
			@endif
		</div>
		<div class="box-body">
			<div style="display: flex;">
				<a href="{{route('empresas.create')}}" class="btn btn-success" style="margin-right: 5px">
					<i class="fa fa-plus fa-md" aria-hidden="true"></i> Cadastrar
				</a>

				<form action="{{route('empresas.search')}}" method="GET" role="search">
					{{ csrf_field() }}
					<div class="input-group">
						<input type="text" class="form-control" name="q" placeholder="Buscar empresas" value="{{ $query }}">

						<span class="input-group-btn">
							<button type="submit" class="btn btn-default">
								<span class="fa fa-search"></span>
							</button>
						</span>
					</div>
				</form>
			</div>

			@if(count($empresas))
			<table class="table table-hover" style="margin-top: 20px">
				<thead>
					<th>#</th>
					<th>CNPJ</th>
					<th>Nome</th>
					<th>Criado em</th>
					<th>Ações</th>
				</thead>
				<tbody>
					@foreach($empresas as $index => $empresa)
					<tr>
						<td>{{ $index + 1 + $perPage * ($page - 1) }}</td>
						<td>{{ StringHelpers::formatCpfCnpj($empresa->cnpj) }}</td>
						<td>{{ $empresa->nome }}</td>
						<td>{{ $empresa->created_at->format('d/m/Y H:i') }}</td>
						<td>
							<!-- {{ Form::open(['route' => ['empresas.destroy', $empresa->id], 'method' => 'delete']) }} -->
							<div class='btn-group'>
								<a href="{{ route('empresas.edit', [$empresa->id]) }}" class='btn btn-primary btn-sm'>
									<i class="fa fa-pencil-square-o" aria-hidden="true"></i>
								</a>
								<!-- {{
									Form::button(
										'<i class="fa fa-trash-o" aria-hidden="true"></i>',
										['type' => 'submit', 'class' => 'btn btn-danger btn-sm', 'onclick' => "return confirm('Você tem certeza?')"]
									)
								}} -->
							</div>
							<!-- {{ Form::close() }} -->
						</td>
					</tr>
					@endforeach
				</tbody>
			</table>

			<div style="text-align: center">
				{{ $empresas->render() }}
			</div>

			@else
			<div style="margin-top: 20px; text-align: center">
				<h4>Nenhuma empresa encontrada.</h4>
			</div>

			@endif
		</div>
	</div>
</section>
@endsection