routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false, 'reset' => false, 'verify' => false]);

Route::group(['middleware' => ['auth', 'verified']], function () {
    Route::get('/', function () {
        return redirect(route('home'));
    });

    Route::get('/home', 'ApplicationController@index')->name('home');

    Route::resource('/prestadores_servicos', '\App\Http\Controllers\PrestadorServicoController');
    Route::get('/prestadores_servicos/buscar', '\App\Http\Controllers\PrestadorServicoController@search')->name('prestadores_servicos.search');

    Route::get('/contratos', '\App\Http\Controllers\App\ContratoController@index');
    Route::get('/contratos/create', '\App\Http\Controllers\App\ContratoController@create')->name('contratos.create');

    Route::group([], function () {
        Route::get('/admin', 'AdminController@index')->name('admin');

        Route::group(['prefix' => 'admin'], function () {
            Route::resource('/empresas', '\App\Http\Controllers\Admin\EmpresaController')->except(['show']);
            Route::get('/empresas/buscar', '\App\Http\Controllers\Admin\EmpresaController@search')->name('empresas.search');

            Route::resource('/usuarios', '\App\Http\Controllers\Admin\UsuarioController')->except(['show']);
            Route::get('/usuarios/buscar', '\App\Http\Controllers\Admin\UsuarioController@search')->name('usuarios.search');

            Route::resource('/aliquota_imposto_renda', '\App\Http\Controllers\Admin\AliquotaImpostoRendaController')->except(['show']);
        });
    });
});

app/Http/Controllers/Admin/UsuarioController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Model\Usuario;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Models\Role;

class UsuarioController extends Controller
{
    protected $perPage = 20;

    /**
     * Display a paginated listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $perPage = $this->perPage;
        $page = $request->page ? $request->page : 1;
        $usuarios = Usuario::paginate($this->perPage);

        return view('admin.usuarios.index', compact('usuarios', 'page', 'perPage'))->with('query', $request->q);
    }

    /**
     * Display a filtered paginated listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function search(Request $request)
    {
        $perPage = $this->perPage;
        $page = $request->page ? $request->page : 1;
        $query = '%' . $request->q . '%';

        $usuarios = Usuario::where('email', 'LIKE', $query)
            ->orWhere('nome', 'LIKE', $query)
            ->paginate($this->perPage);

        return view('admin.usuarios.index', compact('usuarios', 'page', 'perPage'))->with('query', $request->q);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $rolesNames = Role::all()->pluck('name')->toArray();
        $roles = array_combine($rolesNames, $rolesNames);

        return view('admin.usuarios.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'nome' => 'required|string|max:255',
            'telefone' => 'nullable|string|between:10,11',
            'email' => 'required|string',
            'senha' => 'required|string|min:6'
        ]);

        $data['password'] = Hash::make($data['senha']);
        $data['email_verified_at'] = new \DateTime();

        unset($data['senha']);

        $usuario = Usuario::create($data);
        $usuario->assignRole($request->role_name);

        $status = 'O usuário ' . $usuario->nome . ' foi cadastrado com sucesso.';

        return redirect(route('usuarios.index'))->with('status', $status);
    }

    public function edit($id)
    {
        $usuario = Usuario::findOrfail($id);

        return view('admin.usuarios.edit', compact('usuario'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $data = $request->validate([
            'nome' => 'required|string|max:255',
            'email' => 'required|string',
            'telefone' => 'nullable|string|between:10,11',
            'senha' => 'nullable|string|min:6'
        ]);

        if ($data['senha']) {
            $data['password'] = Hash::make($data['senha']);
        }

        unset($data['senha']);

        $usuario = Usuario::findOrfail($request->usuario)->update($data);

        $status = 'O usuario ' . $usuario['nome'] . ' foi atualizado com sucesso.';

        return redirect(route('usuarios.index'))->with('status', $status);
    }

    public function destroy($id)
    {
        $usuario = Usuario::findOrfail($id);

        $usuario->delete();

        return redirect(route('usuarios.index'));
    }
}

resources/views/admin/usuarios/create.blade.php
@extends('layouts.admin')
@section('main')
<section class="content">
	<div class="box box-primary">
		<div class="box-header">
			<h3>Cadastrar usuário</h3>
		</div>
		<div class="box-body">
			<form action="{{ route('usuarios.store') }}" method="post">
				@csrf
				<input type="hidden" name="usuario_id">

				<div class="row">
					<div class="form-group col-sm-6">
						<label for="">Nome</label>
						<input type="text" name="nome" value="{{ old('nome') }}" class="form-control">
						@error('nome')
						<div class="text-danger">{{ $message }}</div>
						@enderror
					</div>
				</div>

				<div class="row">
					<div class="form-group col-sm-6">
						<label for="">E-mail</label>
						<input type="email" name="email" value="{{ old('email') }}" id="email" class="form-control" placeholder="nome@exemplo.com">
						@error('email')
						<div class="text-danger">{{ $message }}</div>
						@enderror
					</div>
				</div>

				<div class="row">
					<div class="form-group col-sm-6">
						<label for="telefone">Telefone</label>
						<input type="text" name="telefone" value="{{ old('telefone') }}" id="telefone" class="form-control" placeholder="(00) 0000-0000">
						@error('telefone')
						<div class="text-danger">{{ $message }}</div>
						@enderror
					</div>
				</div>

				<div class="row">
					<div class="form-group col-sm-6">
						<label for="">Senha</label>
						<input type="password" name="senha" class="form-control">
						@error('senha')
						<div class="text-danger">{{ $message }}</div>
						@enderror
					</div>
				</div>

				<div class="row">
					<div class="form-group col-sm-6">
						<label for="role_name">Função</label>
						{!! Form::select('role_name', $roles, 'consultor', ['class' => 'form-control']); !!}
					</div>
				</div>

				<div class="form-group">
					<button class="btn btn-primary" type="submit">Salvar</button>

					<a href="{{url('/admin/usuarios')}}">
						<button class="btn btn-default" type="button">Cancelar</button>
					</a>
				</div>
			</form>
		</div>
	</div>

	<script src="{{ URL::asset('js/InputMasks.js') }}"></script>
</section>
@endsection

resources/views/admin/usuarios/edit.blade.php
@extends('layouts.admin')
@section('main')
<section class="content">
	<div class="box box-primary">
		<div class="box-header">
			<h3>Editar usuário ({{ $usuario->nome }})</h3>
		</div>
		<div class="box-body">
			<form action="{{route('usuarios.update', [$usuario->id])}}" method="post">
				@method('PUT')
				@csrf
				<input type="hidden" name="usuario_id" value="{{ $usuario->id }}">

				<div class="row">
					<div class="form-group col-sm-6">
						<label for="">Nome</label>
						<input type="text" name="nome" value="{{ $usuario->nome }}" class="form-control">
						@error('nome')
						<div class="text-danger">{{ $message }}</div>
						@enderror
					</div>
				</div>

				<div class="row">
					<div class="form-group col-sm-6">
						<label for="">E-mail</label>
						<input type="email" name="email" value="{{ $usuario->email }}" id="email" class="form-control">
						@error('email')
						<div class="text-danger">{{ $message }}</div>
						@enderror
					</div>
				</div>

				<div class="row">
					<div class="form-group col-sm-6">
						<label for="telefone">Telefone</label>
						<input type="text" name="telefone" value="{{ $usuario->telefone }}" id="telefone" class="form-control" placeholder="(00) 0000-0000">
						@error('telefone')
						<div class="text-danger">{{ $message }}</div>
						@enderror
					</div>
				</div>

				<div class="row">
					<div class="form-group col-sm-6">
						<label for="">Nova senha</label>
						<input type="password" name="senha" class="form-control" placeholder="Senha">
						@error('senha')
						<div class="text-danger">{{ $message }}</div>
						@enderror
					</div>
				</div>

				<div class="form-group">
					<button class="btn btn-primary" type="submit">Salvar</button>

					<a href="{{url('/admin/usuarios')}}">
						<button class="btn btn-default" type="button">Cancelar</button>
					</a>
				</div>
			</form>
		</div>
	</div>

	<script src="{{ URL::asset('js/InputMasks.js') }}"></script>
</section>
@endsection

resources/views/admin/usuarios/index.blade.php
@extends('layouts.admin')
@section('main')
<section class="content">
	<div class="box box-primary">
		<div class="box-header">
			<h3>Usuários</h3>
			@if (session('status'))
			<div class="alert alert-success">
				{{ session('status') }}
			</div>
			@endif
		</div>
		<div class="box-body">
			<div style="display: flex;">
				<!-- <a href="{{route('usuarios.create')}}" class="btn btn-success" style="margin-right: 5px">
					<i class="fa fa-plus fa-md" aria-hidden="true"></i> Cadastrar
				</a> -->

				<form action="{{route('usuarios.search')}}" method="GET" role="search">
					{{ csrf_field() }}
					<div class="input-group">
						<input type="text" class="form-control" name="q" placeholder="Buscar usuários" value="{{ $query }}">

						<span class="input-group-btn">
							<button type="submit" class="btn btn-default">
								<span class="fa fa-search"></span>
							</button>
						</span>
					</div>
				</form>
			</div>

			@if(count($usuarios))
			<table class="table table-hover" style="margin-top: 20px">
				<thead>
					<th>#</th>
					<th>Nome</th>
					<th>E-mail</th>
					<th>Função</th>
					<th>Criado em</th>
					<th>Ações</th>
				</thead>
				<tbody>
					@foreach($usuarios as $index => $usuario)
					<tr>
						<td>{{ $index + 1 + $perPage * ($page - 1) }}</td>
						<td>{{ $usuario->nome }}</td>
						<td>{{ $usuario->email }}</td>
						<td>
							@foreach($usuario->roles as $role)
							<span>{{ $role->name }}</span>
							@endforeach
						</td>
						<td>{{ $usuario->created_at->format('d/m/Y H:i') }}</td>
						<td>
							<!-- {{ Form::open(['route' => ['usuarios.destroy', $usuario->id], 'method' => 'delete']) }} -->
							<div class='btn-group'>
								<a href="{{ route('usuarios.edit', [$usuario->id]) }}" class='btn btn-primary btn-sm'>
									<i class="fa fa-pencil-square-o" aria-hidden="true"></i>
								</a>
								<!-- {{
									Form::button(
										'<i class="fa fa-trash-o" aria-hidden="true"></i>',
										['type' => 'submit', 'class' => 'btn btn-danger btn-sm', 'onclick' => "return confirm('Você tem certeza?')"]
									)
								}} -->
							</div>
							<!-- {{ Form::close() }} -->
						</td>
					</tr>
					@endforeach
				</tbody>
			</table>

			<div style="text-align: center">
				{{ $usuarios->render() }}
			</div>

			@else
			<div style="margin-top: 20px; text-align: center">
				<h4>Nenhuma informação encontrada.</h4>
			</div>

			@endif
		</div>
	</div>
</section>
@endsection