routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false, 'reset' => false, 'verify' => false]);

Route::group(['middleware' => ['auth', 'verified']], function () {
    Route::get('/', function () {
        return redirect(route('home'));
    });

    Route::get('/home', 'ApplicationController@index')->name('home');

    Route::resource('/prestadores_servicos', '\App\Http\Controllers\PrestadorServicoController');
    Route::get('/prestadores_servicos/buscar', '\App\Http\Controllers\PrestadorServicoController@search')->name('prestadores_servicos.search');

    Route::get('/contratos', '\App\Http\Controllers\App\ContratoController@index');
    Route::get('/contratos/create', '\App\Http\Controllers\App\ContratoController@create')->name('contratos.create');

    Route::group([], function () {
        Route::get('/admin', 'AdminController@index')->name('admin');

        Route::group(['prefix' => 'admin'], function () {
            Route::resource('/empresas', '\App\Http\Controllers\Admin\EmpresaController')->except(['show']);
            Route::get('/empresas/buscar', '\App\Http\Controllers\Admin\EmpresaController@search')->name('empresas.search');

            Route::resource('/usuarios', '\App\Http\Controllers\Admin\UsuarioController')->except(['show']);
            Route::get('/usuarios/buscar', '\App\Http\Controllers\Admin\UsuarioController@search')->name('usuarios.search');

            Route::resource('/aliquota_imposto_renda', '\App\Http\Controllers\Admin\AliquotaImpostoRendaController')->except(['show']);
        });
    });
});

app/Http/Controllers/Admin/AliquotaImpostoRendaController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Model\AliquotaImpostoRenda;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AliquotaImpostoRendaController extends Controller
{
    public function index(Request $request)
    {
        $aliquotas = AliquotaImpostoRenda::all();

        return view('admin.aliquota_imposto_renda.index', compact('aliquotas'));
    }

    public function edit($id)
    {
        $aliquota = AliquotaImpostoRenda::findOrfail($id);

        return view('admin.aliquota_imposto_renda.edit', compact('aliquota'));
    }

    public function update(Request $request, $id)
    {
        $data = $request->validate([
            'faixa_inicio' => 'required|numeric',
            'faixa_fim' => 'required|numeric',
            'aliquota' => 'required|numeric',
            'deducao' => 'required|numeric'
        ]);

        AliquotaImpostoRenda::findOrfail($id)->update($data);

        $status = 'A aliquota foi atualizada com sucesso.';

        return redirect(route('aliquota_imposto_renda.index'))->with('status', $status);
    }
}

resources/views/admin/aliquota_imposto_renda/edit.blade.php
@extends('layouts.admin')
@section('main')
<section class="content">
	<div class="box box-primary">
		<div class="box-header">
			<h3>Editar Alíquota IR</h3>
		</div>
		<div class="box-body">
			<form action="{{route('aliquota_imposto_renda.update', [$aliquota->id])}}" method="post">
				@method('PUT')
				@csrf

				<div class="row">
					<div class="form-group col-sm-3">
						<label for="">Faixa - início (R$)</label>
						<input name="faixa_inicio" id="faixa_inicio" value="{{$aliquota->faixa_inicio}}" class="form-control" placeholder="0.00">
						@error('faixa_inicio')
						<div class="text-danger">{{ $message }}</div>
						@enderror
					</div>
				</div>

				<div class="row">
					<div class="form-group col-sm-3">
						<label for="">Faixa - fim (R$)</label>
						<input name="faixa_fim" id="faixa_fim" value="{{$aliquota->faixa_fim}}" class="form-control" placeholder="0.00">
						@error('faixa_fim')
						<div class="text-danger">{{ $message }}</div>
						@enderror
					</div>
				</div>

				<div class="row">
					<div class="form-group col-sm-3">
						<label for="">Alíquota (%)</label>
						<input type="text" name="aliquota" value="{{$aliquota->aliquota}}" class="form-control" placeholder="0.0">
						@error('aliquota')
						<div class="text-danger">{{ $message }}</div>
						@enderror
					</div>
				</div>

				<div class="row">
					<div class="form-group col-sm-3">
						<label for="">Parcela a deduzir (R$)</label>
						<input type="text" name="deducao" value="{{$aliquota->deducao}}" class="form-control" placeholder="0.0">
						@error('deducao')
						<div class="text-danger">{{ $message }}</div>
						@enderror
					</div>
				</div>

				<div class="form-group">
					<button class="btn btn-primary" type="submit">Salvar</button>

					<a href="{{url('/admin/aliquota_imposto_renda')}}">
						<button class="btn btn-default" type="button">Cancelar</button>
					</a>
				</div>
			</form>
		</div>
	</div>
</section>
@endsection

resources/views/admin/aliquota_imposto_renda/index.blade.php
@extends('layouts.admin')
@section('main')
<section class="content">
	<div class="box box-primary">
		<div class="box-header">
			<h3>Alíquota do Imposto de Renda</h3>
			@if (session('status'))
				<div class="alert alert-success">
					{{ session('status') }}
				</div>
			@endif
		</div>
		<div class="box-body">
			<!-- <div style="display: flex;">
				<a href="{{route('aliquota_imposto_renda.create')}}" class="btn btn-success" style="margin-right: 5px">
					<i class="fa fa-plus fa-md" aria-hidden="true"></i> Cadastrar
				</a>
			</div> -->

			@if(count($aliquotas))
			<table class="table table-hover" style="margin-top: 20px">
				<thead>
					<th>#</th>
					<th>Base de cálculo</th>
					<th>Alíquota</th>
					<th>Parcela a deduzir</th>
					<th>Ações</th>
				</thead>
				<tbody>
					@foreach($aliquotas as $index => $aliquota)
					<tr>
						<td>{{ $index + 1 }}</td>

						@if($aliquota->faixa_fim)
						<td>De R${{ $aliquota->faixa_inicio }} até R${{ $aliquota->faixa_fim }}</td>
						@else
						<td>Acima de R${{ $aliquota->faixa_inicio }}</td>
						@endif

						@if($aliquota->aliquota != 0)
						<td>{{ floor(($aliquota->aliquota*100))/100 }}%</td>
						@else
						<td>isento</td>
						@endif

						@if($aliquota->deducao != 0)
						<td>R${{ $aliquota->deducao }}</td>
						@else
						<td>isento</td>
						@endif

						<td>
							<!-- {{ Form::open(['route' => ['aliquota_imposto_renda.destroy', $aliquota->id], 'method' => 'delete']) }} -->
							<div class='btn-group'>
								<a href="{{ route('aliquota_imposto_renda.edit', [$aliquota->id]) }}" class='btn btn-primary btn-sm'>
									<i class="fa fa-pencil-square-o" aria-hidden="true"></i>
								</a>
								<!-- {{
									Form::button(
										'<i class="fa fa-trash-o" aria-hidden="true"></i>', 
										['type' => 'submit', 'class' => 'btn btn-danger btn-sm', 'onclick' => "return confirm('Você tem certeza?')"]
									) 
								}} -->
							</div>
							<!-- {{ Form::close() }} -->
						</td>
					</tr>
					@endforeach
				</tbody>
			</table>

			@else
			<div style="margin-top: 20px; text-align: center">
				<h4>Nenhuma aliquota encontrada.</h4>
			</div>

			@endif
		</div>
	</div>
</section>
@endsection