routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false, 'reset' => false, 'verify' => false]);

Route::group(['middleware' => ['auth', 'verified']], function () {
    Route::get('/', function () {
        return redirect(route('home'));
    });

    Route::get('/home', 'ApplicationController@index')->name('home');

    Route::resource('/prestadores_servicos', '\App\Http\Controllers\PrestadorServicoController');
    Route::get('/prestadores_servicos/buscar', '\App\Http\Controllers\PrestadorServicoController@search')->name('prestadores_servicos.search');

    Route::get('/contratos', '\App\Http\Controllers\App\ContratoController@index');
    Route::get('/contratos/create', '\App\Http\Controllers\App\ContratoController@create')->name('contratos.create');

    Route::group([], function () {
        Route::get('/admin', 'AdminController@index')->name('admin');

        Route::group(['prefix' => 'admin'], function () {
            Route::resource('/empresas', '\App\Http\Controllers\Admin\EmpresaController')->except(['show']);
            Route::get('/empresas/buscar', '\App\Http\Controllers\Admin\EmpresaController@search')->name('empresas.search');

            Route::resource('/usuarios', '\App\Http\Controllers\Admin\UsuarioController')->except(['show']);
            Route::get('/usuarios/buscar', '\App\Http\Controllers\Admin\UsuarioController@search')->name('usuarios.search');

            Route::resource('/aliquota_imposto_renda', '\App\Http\Controllers\Admin\AliquotaImpostoRendaController')->except(['show']);
        });
    });
});

resources/views/app/prestadores_servicos/create.blade.php
@extends('app.home')

@section('content')
<h3 style="margin:15px 0">Cadastrar Prestador Serviço</h3>
<div class="card border">
    <div class="card-body">
        <form action="/prestadores_servicos" method="POST">
            @csrf
            <div class="row">
                <div class="form-group col-sm-6">
                    <label for="nome">Nome</label>
                    <input type="text" class="form-control" name="nome" value="{{old('nome')}}" id="nome" placeholder="Nome completo">
                    @error('nome')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group col-sm-3">
                    <label for="cpf">CPF</label>
                    <input type="text" class="form-control" name="cpf" value="{{old('cpf')}}" id="cpf" placeholder="000.000.000-00">
                    @error('cpf')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group col-sm-3">
                    <label for="dataNas">Data de Nascimento</label>
                    {{ Form::date('data_nascimento', old('dataNas'), ['class' => 'form-control']) }}
                    @error('data_nascimento')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>

            <div class="row">
                <div class="form-group col-sm-3">
                    <label for="inscricao_municipal">Inscrição municipal</label>
                    <input type="text" class="form-control" name="inscricao_municipal" value="{{old('inscricao_municipal')}}" id="inscricao_municipal" placeholder="">
                    @error('inscricao_municipal')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group col-sm-2">
                    <label for="cep">CEP</label>
                    <input type="text" class="form-control" name="cep" value="{{old('cep')}}" id="cep" placeholder="Ex.: 76900-800">
                    @error('cep')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group col-sm-5">
                    <label for="endereco">Endereço</label>
                    <input type="text" class="form-control" name="endereco" value="{{old('endereco')}}" id="endereco" placeholder="Ex.: Av. Brasil">
                    @error('endereco')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group col-sm-2">
                    <label for="numero">Numero</label>
                    <input type="text" class="form-control" name="numero" value="{{old('numero')}}" id="numero" placeholder="Ex.: 1000">
                    @error('numero')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>

            <div class="row">
                <div class="form-group col-sm-6">
                    <label for="bairro">Bairro</label>
                    <input type="text" class="form-control" name="bairro" value="{{old('bairro')}}" id="bairro">
                    @error('bairro')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group col-sm-6">
                    <label for="cidade">Cidade</label>
                    <select name="cidade" value="{{old('cidade')}}" id="" class="form-control">
                        <option value="null">...</option>
                        @foreach ($cidades as $cidade)
                        <option value="{{$cidade->id}}">{{$cidade->nome}}</option>
                        @endforeach
                    </select>
                    @error('cidade')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>

            <div class="row">
                <div class="form-group col-sm-2">
                    <label for="rg">RG</label>
                    <input type="text" class="form-control" name="rg" value="{{old('rg')}}" id="rg" placeholder="Ex.: 12.345.567-8">
                    @error('rg')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group col-sm-2">
                    <label for="rg_orgao_emissor">Órgão emissor</label>
                    <input type="text" class="form-control" name="rg_orgao_emissor" value="{{old('rg_orgao_emissor')}}" id="rg_orgao_emissor" placeholder="Ex.: SSP">
                    @error('rg_orgao_emissor')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group col-sm-3">
                    <label for="pis_nit">PIS/NIT</label>
                    <input type="text" class="form-control" name="pis_nit" value="{{old('pis_nit')}}" id="pis_nit" placeholder="Insira o PIS ou NIT">
                    @error('pis_nit')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group col-sm-5">
                    <label for="nome_mae">Nome da mãe</label>
                    <input type="nome_mae" class="form-control" name="nome_mae" value="{{old('nome_mae')}}" id="nome_mae" placeholder="Informar caso não houver PIS/NIT">
                    @error('nome_mae')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>

            <div class="row">
                <div class="form-group col-sm-5">
                    <label for="email">Email</label>
                    <input type="email" class="form-control" name="email" value="{{old('email')}}" id="email" placeholder="nome@exemplo.com">
                    @error('email')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group col-sm-4">
                    <label for="telefone">Telefone</label>
                    <input type="telefone" class="form-control" name="telefone" value="{{old('telefone')}}" id="telefone" placeholder="Ex.: (00) 0000-0000">
                    @error('telefone')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group col-sm-3">
                    <label class="form-check-label" for="renda_eclesiatica">Renda eclesiástica?</label>

                    <div style="margin-top: 15px">
                        <div class="form-check form-check-inline">
                            <input checked type="radio" class="form-check-input" value="0" name="renda_eclesiatica" id="is_not_renda_eclesiatica">
                            <label class="form-check-label" for="is_not_renda_eclesiatica">Não</label>
                        </div>

                        <div class="form-check form-check-inline">
                            <input type="radio" class="form-check-input" value="1" name="renda_eclesiatica" id="is_renda_eclesiatica">
                            <label class="form-check-label" for="is_renda_eclesiatica">Sim</label>
                        </div>
                    </div>
                </div>
            </div>

            <button type="submit" class="btn btn-primary btn-sm">Salvar</button>
            <a href="{{ route('prestadores_servicos.index') }}" class="btn btn-default btn-sm btn-cancel">Cancelar</a>
        </form>
    </div>
</div>
    <script src="{{ URL::asset('js/InputMasks.js') }}"></script>
@endsection

resources/views/app/prestadores_servicos/edit.blade.php
@extends('app.home')

@section('content')
<h3 style="margin:15px 0">Editar Prestador de Serviço</h3>
<div class="card border">
    <div class="card-body">
        <form action="{{route('prestadores_servicos.update', [$prestador->id])}}" method="POST">
            @method('PUT')
            @csrf

            <div class="row">
                <div class="form-group col-sm-6">
                    <label for="nome">Nome</label>
                    <input type="text" class="form-control" name="nome" value="{{$prestador->nome}}" id="nome" placeholder="Nome Completo">
                    @error('nome')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group col-sm-3">
                    <label for="cpf">CPF</label>
                    <input type="text" class="form-control" name="cpf" value="{{$prestador->cpf}}" id="cpf" placeholder="000.000.000-00">
                    @error('cpf')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group col-sm-3">
                    <label for="dataNas">Data de Nascimento</label>
                    {{ Form::date('data_nascimento', $prestador->data_nascimento, ['class' => 'form-control']) }}
                    @error('data_nascimento')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>

            <div class="row">
                <div class="form-group col-sm-3">
                    <label for="inscricao_municipal">Inscrição municipal</label>
                    <input type="text" class="form-control" name="inscricao_municipal" value="{{$prestador->inscricao_municipal}}" id="inscricao_municipal" placeholder="">
                    @error('inscricao_municipal')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group col-sm-2">
                    <label for="cep">CEP</label>
                    <input type="text" class="form-control" name="cep" value="{{$prestador->cep}}" id="cep">
                    @error('cep')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group col-sm-5">
                    <label for="endereco">Endereço</label>
                    <input type="text" class="form-control" name="endereco" value="{{$prestador->endereco}}" id="endereco">
                    @error('endereco')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group col-sm-2">
                    <label for="numero">Numero</label>
                    <input type="text" class="form-control" name="numero" value="{{$prestador->numero}}" id="numero" placeholder="Número">
                    @error('numero')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>

            <div class="row">
                <div class="form-group col-sm-6">
                    <label for="bairro">Bairro</label>
                    <input type="text" class="form-control" name="bairro" value="{{$prestador->bairro}}" id="bairro">
                    @error('bairro')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group col-sm-6">
                    <label for="cidade">Cidade</label>
                    <select name="cidade" value="{{old('cidade')}}" id="" class="form-control">
                        <option value="null">...</option>
                        @foreach ($cidades as $cidade)
                        @if($cidade->id == $prestador->cidade_id)
                        <option value="{{$cidade->id}}" selected>{{$cidade->nome}}</option>
                        @else
                        <option value="{{$cidade->id}}">{{$cidade->nome}}</option>
                        @endif
                        @endforeach
                    </select>
                    @error('cidade')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>

            <div class="row">
                <div class="form-group col-sm-2">
                    <label for="rg">RG</label>
                    <input type="text" class="form-control" name="rg" value="{{$prestador->rg}}" id="rg" placeholder="0000000">
                    @error('rg')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group col-sm-2">
                    <label for="rg_orgao_emissor">Órgão emissor</label>
                    <input type="text" class="form-control" name="rg_orgao_emissor" value="{{$prestador->rg_orgao_emissor}}" id="rg_orgao_emissor" placeholder="Ex.: SSP">
                    @error('rg_orgao_emissor')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group col-sm-3">
                    <label for="pis_nit">PIS/NIT</label>
                    <input type="text" class="form-control" name="pis_nit" value="{{$prestador->pis_nit}}" id="pis_nit" placeholder="Insira o PIS ou NIT">
                    @error('pis_nit')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group col-sm-5">
                    <label for="nome_mae">Nome da mãe</label>
                    <input type="nome_mae" class="form-control" name="nome_mae" value="{{$prestador->nome_mae}}" id="nome_mae">
                    @error('nome_mae')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>

            <div class="row">
                <div class="form-group col-sm-5">
                    <label for="email">Email</label>
                    <input type="email" class="form-control" name="email" value="{{$prestador->email}}" id="email">
                    @error('email')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group col-sm-4">
                    <label for="telefone">Telefone</label>
                    <input type="text" class="form-control" name="telefone" value="{{$prestador->telefone}}" id="telefone">
                    @error('telefone')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group col-sm-3">
                    <label class="form-check-label" for="renda_eclesiatica">Renda eclesiástica?</label>

                    <div style="margin-top: 15px">
                        <div class="form-check form-check-inline">
                            @if($prestador->renda_eclesiatica == 0)
                            <input checked type="radio" class="form-check-input" value="0" name="renda_eclesiatica" id="is_not_renda_eclesiatica">
                            @else
                            <input type="radio" class="form-check-input" value="0" name="renda_eclesiatica" id="is_not_renda_eclesiatica">
                            @endif
                            <label class="form-check-label" for="is_not_renda_eclesiatica">Não</label>
                        </div>

                        <div class="form-check form-check-inline">
                            @if($prestador->renda_eclesiatica == 1)
                            <input checked type="radio" class="form-check-input" value="1" name="renda_eclesiatica" id="is_renda_eclesiatica">
                            @else
                            <input type="radio" class="form-check-input" value="1" name="renda_eclesiatica" id="is_renda_eclesiatica">
                            @endif
                            <label class="form-check-label" for="is_renda_eclesiatica">Sim</label>
                        </div>
                    </div>
                </div>
            </div>

            <button type="submit" class="btn btn-primary btn-sm">Salvar</button>
            <a href="{{ route('prestadores_servicos.index') }}" class="btn btn-default btn-sm btn-cancel">Cancelar</a>
        </form>
    </div>
</div>
<script src="{{ URL::asset('js/InputMasks.js') }}"></script>
@endsection

resources/views/app/prestadores_servicos/index.blade.php
@extends('app.home')

@section('content')
<h3 style="margin:15px 0">Prestadores de serviços</h3>
@if (session('status'))
    <div class="alert alert-success">
        {{ session('status') }}
    </div>
@endif
<div class="card border">
    <div class="card-body">
        <div style="display: flex;">
            <a href="{{route('prestadores_servicos.create')}}" class="btn btn-success" style="margin-right: 5px">
                <i class="fa fa-plus fa-md" aria-hidden="true"></i> Cadastrar
            </a>

            <form action="{{route('prestadores_servicos.search')}}" method="GET" role="search">
                {{ csrf_field() }}
                <div class="input-group">
                    <input type="text" class="form-control" name="q" placeholder="Buscar prestadores de serviços" value="{{ $query }}">

                    <span class="input-group-btn">
                        <button type="submit" class="btn btn-default">
                            <span class="fa fa-search"></span>
                        </button>
                    </span>
                </div>
            </form>
        </div>

        @if(count($prestadores))
        <table class="table table-hover" style="margin-top: 20px">
            <thead>
                <th>#</th>
                <th>CPF</th>
                <th>Nome</th>
                <th>Criado em</th>
                <th>Ações</th>
            </thead>
            <tbody>
                @foreach($prestadores as $index => $prestador)
                <tr>
                    <td>{{ $index + 1 + $perPage * ($page - 1) }}</td>
                    <td>{{ StringHelpers::formatCpfCnpj($prestador->cpf) }}</td>
                    <td>{{ $prestador->nome }}</td>
                    <td>{{ $prestador->created_at->format('d/m/Y H:i') }}</td>
                    <td>
                        {{ Form::open(['route' => ['prestadores_servicos.destroy', $prestador->id], 'method' => 'delete']) }}
                        <div class='btn-group'>
                            <a href="{{ route('prestadores_servicos.edit', [$prestador->id]) }}" class='btn btn-primary btn-sm'>
                                Editar
                            </a>
                            <!-- {{
                                Form::button(
                                    '<i class="fa fa-trash-o" aria-hidden="true"></i>',
                                    ['type' => 'submit', 'class' => 'btn btn-danger btn-sm', 'onclick' => "return confirm('Você tem certeza?')"]
                                )
                            }} -->
                        </div>
                        {{ Form::close() }}
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>

        <div style="text-align: center">
            {{ $prestadores->render() }}
        </div>

        @else
        <div style="margin-top: 20px; text-align: center">
            <h4>Nenhuma informação encontrada.</h4>
        </div>

        @endif
    </div>
</div>
@endsection